# To run a specific version of Jaeger, use environment variable, e.g.:
#     JAEGER_VERSION=2.0.0 HOTROD_VERSION=1.63.0 docker compose up

services:
  jaeger:
    image: ${REGISTRY:-}jaegertracing/jaeger:${JAEGER_VERSION:-latest}
    # No ports exposed directly to host
    environment:
      - LOG_LEVEL=debug
    networks:
      - jaeger-example
      
  nginx:
    image: nginx:alpine
    ports:
      - "16686:80"
      - "4317:4317"  # OTLP gRPC port
      - "4318:80"    # OTLP HTTP port (mapped to Nginx HTTP port)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - jaeger-example
    depends_on:
      - jaeger

  hotrod:
    image: ${REGISTRY:-}jaegertracing/example-hotrod:${HOTROD_VERSION:-latest}
    # To run the latest trunk build, find the tag at Docker Hub and use the line below
    # https://hub.docker.com/r/jaegertracing/example-hotrod-snapshot/tags
    #image: jaegertracing/example-hotrod-snapshot:0ab8f2fcb12ff0d10830c1ee3bb52b745522db6c
    ports:
      - "8080:8080"
      - "8083:8083"
    command: [ "all" ]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://nginx:80/v1/traces
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic YWRtaW46cGFzc3dvcmQ=
    networks:
      - jaeger-example
    depends_on:
      - nginx

networks:
  jaeger-example: